### ISSUE TITLE
Scene description interface/API

### ISSUE THREAD

**Issue by virtualritz** [cessen/psychopath#14]
I suggest to consider 3Delight's [NSI](https://nsi.readthedocs.io) as a scene description API/interface for Psychopath. 
NSI is to the RenderMan interface (Ri) what OSL is to RenderMan SL.
NSI's design [is informed](https://nsi.readthedocs.io/en/latest/background.html) by extending the strengths and weeding out the shortcomings of the Ri.

The 3Delight team will support you if you do this (the API is free to implement for anyone).
The strongest argument from an end user's side is that Psychopath would work, more or less out of the box, with Houdini, Maya, Katana, Cinema4D, and soon, Blender. All the NSI-based DCC plug-ins for 3Delight are open source @ GitLab. 3Delight has an API version that loads the renderer library dynamically at runtime. Adding an option to these plug-ins to load another renderer instead is not difficult in which case you could even share the codebase.

Oh, there is also an open source Pixar Hydra delegate for NSI. So that would mean full USD support in Psychopath, as a side effect. And w/o ever touching this pile of designed-by-committee rubbish of a scene description format.

The NSI API is just a few calls of C [in a single header](https://nsi.readthedocs.io/en/latest/nsi.h.html). Dead easy to expose from Rust.

I also wrote a [crappy Rust binding](https://crates.io/crates/nsi) on top of it that I vow to improve as I become more proficient in this language. :)

Writing exporters for this API is a bliss as it doesn't carry state in a way that most other renderer APIs do.

P.S.: I am actually working with the 3Delight team, cleaning the NSI spec. up for a v1.0 release this year.

P.P.S.: NSI currently lacks nodes for quadrics, patches and (trimmed) NURBS (metaballs could also be added). NURBS at least will be part of v1.0. I'm very open for input on how these should look, API wise.

**Comment by cessen** [comment]
Thanks for the suggestion!

I'm definitely aware of NSI, and I might consider it in the far future.  But right now just using my own bespoke API provides more flexibility in terms of development.  I don't have to worry about correctly supporting a foreign API this way, among other things.

Having said that, supporting a standardized, well-supported API obviously also brings a lot of benefits, as you outlined.  So I'll definitely keep this in mind if I decide to turn Psychopath into something serious in the future.  But right now, none of those benefits are important to me: Psychopath isn't a product, I only care about it working with Blender, and using my own bespoke API gives me more flexibility and room to play.
