### ISSUE TITLE
Add support for bicubic bezier patches

### ISSUE THREAD

**Issue by cessen** [cessen/psychopath#7]
The C++ version of Psychopath had support for direct rendering of bicubic bezier patches.  This is not only fun (allows direct rendering of the Utah tea set!), but also useful for testing that the machinery for on-the-fly refinement of curved surfaces (and eventually displacements) works correctly.  Subdivision surfaces are more useful, but are also more complex.  Having this simpler test case will be useful.

- Use progressive splitting while ray tracing to refine the surface.
- Use bounding box size during refinement to determine when refinement should terminate (for now use a fixed target size).
- Create a quad out of two triangles for final hit/miss testing and UV's, but use the bounding box as the error bounds of the hit point.

This should be enough to figure out the basics.  An interesting thing to explore will be keeping the final hit/miss test watertight, since refinement can be different between two adjacent areas of the surface.

(I'm tempted to go the way I did in the C++ Psychopath and just use the bounding boxes themselves for the hit/miss test, but I'm concerned how that may affect e.g. texture mapping at grazing angles, etc.  The benefit, though, is that it's guaranteed to be watertight even with completely unrelated adjacent patches.)

Don't worry about adaptive refinement based on ray differentials yet.  That can come later, and should be a relatively straightforward extension once we have ray differentials.

**Comment by virtualritz** [comment]
On a side note, Catmull-Clark subdivision surfaces, after one level of subdivision (can be omitted if the mesh is all quads to start with) can be composed into quad mesh subregions that are, each, the control polygons of bicubic b-spline patch meshes.
And patch mesh is just multiple patches together. And b-spline patches are just a basis matrix change from bezier patches away. 
 
At least one commercial offline renderer has been rendering sds like this for almost 20 years.

**Comment by cessen** [comment]
Yup!  That's what I did in the [C++ version of Psychopath](https://psychopath.io/post/2015_07_16_subdivision_surfaces), and is likely how I will do things again in Rust.

Although, to be pedantic for a moment, this only works precisely for regular parts of the cage (where all vertices are arity 4, and all faces are quads).  Bspline patches can't actually match the true subdivision surface for parts of the cage with vertices of arity less than or greater than 4, nor for parts of the cage with non-quad faces.  Nevertheless, they're still a good approximation, which is generally more than good enough.

**Comment by cessen** [comment]
Closing this, as it's not super relevant anymore.  I do still plan to support Bezier patches, but all the details in this issue are completely irrelevant to the new architecture.
